##READ IN FROM DATA file_path = r'C:\Users\johnc\Desktop\DA12\Python\DA12capstone_Videogame_Monetization\data\your_file_name.csv' df = pd.read_csv(file_path)

In [1]:
import requests
from bs4 import BeautifulSoup as BS
import pandas as pd
import html5lib
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
file_path = r'C:\Users\johnc\Desktop\DA12\Python\DA12capstone_Videogame_Monetization\data\highest_revenue_distribution_copmanies_raw.csv' 
highest_revenue_companies = pd.read_csv(file_path)

In [5]:
highest_revenue_companies=highest_revenue_companies.drop(columns='Ref.')

In [6]:
highest_revenue_companies

,Rank,Company,Headquarter,Revenue
0,1,Sony Interactive Entertainment,"San Mateo, California",$29.8 billion
1,2,Tencent Interactive Entertainment,"Shenzhen, China",$25.5 billion
2,3,Microsoft Gaming,"Redmond, Washington",$21.5 billion
3,4,Nintendo,"Kyoto, Japan",$11.6 billion
4,5,NetEase Games,"Hangzhou, China",$11.5 billion
5,6,Electronic Arts,"Redwood City, California",$7.6 billion
6,7,Epic Games,"Cary, North Carolina",$5.8 billion
7,8,Take-Two Interactive,"New York City, New York",$5.3 billion
8,9,Embracer Group,"Karlstad, Sweden",$4.0 billion
9,10,MiHoYo,"Shanghai, China",$3.8 billion
10,11,Roblox Corporation,"San Mateo, California",$2.8 billion
11,12,Playtika,"Herzliya, Israel",$2.57 billion
12,13,Ubisoft,"Saint-Mandé, France",$2.5 billion
13,14,Nexon,"Minato-ku, Tokyo, Japan",$2.48 billion
14,15,37Games,"Shanghai, China",$2.3 billion
15,16,Square Enix,"Shinjuku, Japan",$2.29 billion
16,17,Oculus Studios,"Menlo Park, California",$2.16 billion
17,18,Bandai Namco Entertainment,"Minato, Tokyo, Japan",$2.1 billion
18,19,Sega,"Shinagawa, Japan",$2.04 billion
19,20,Netmarble,"Seoul, South Korea",$2.0 billion
20,21,NCSoft,"Pangyo, South Korea",$1.99 billion
21,22,Konami Digital Entertainment,"Ginza, Japan",$1.6 billion
22,23,Krafton,"Seongnam, South Korea",$1.43 billion
23,24,Perfect World,"Beijing, China",$1.15 billion
24,25,Garena,Singapore,$1.14 billion
25,26,NetDragon Websoft,"Fuzhou, China",$1.11 billion
26,27,Wizards of the Coast,"Renton, Washington",$1.0 billion
27,28,Scopely,"Culver City, California",$1.0 billion
28,29,Capcom,"Chūō-ku, Osaka, Japan",$978 million
29,30,Keywords Studios,"Leopardstown, Ireland",$780 million
30,31,Kakao Games,"Jeju, South Korea",$725 million
31,32,Niantic,"San Francisco, California",$671 million
32,33,Koei Tecmo,"Yokohama, Japan",$536 million
33,34,Gameloft,"Paris, France",$338 million
34,35,CD Projekt Red,"Warsaw, Poland",$311 million
35,36,Playstudios,"San Francisco, California",$310 million
36,37,Tilting Point,"New York City, New York",$285 million
37,38,Thunderful Group,"Gothenburg, Sweden",$274 million
38,39,Pearl Abyss,"Gwacheon, South Korea",$260 million
39,40,Neowiz Games,"Gyeonggi, South Korea",$250 million
40,41,Paradox Interactive,"Stockholm, Sweden",$248 million
41,42,Marvelous,"Shinagawa, Japan",$190 million
42,43,Enad Global 7,"Stockholm, Sweden",$187 million
43,44,Focus Entertainment,"Paris, France",$187 million
44,45,Nacon,"Lesquin, France",$170 million
45,46,Behaviour Interactive,"Montreal, Canada",$163 million
46,47,Saber Interactive,"Fort Lauderdale, Florida",$161 million
47,48,FromSoftware,"Tokyo, Japan",$152 million
48,49,Team17,"Wakefield, England",$151 million
49,50,Devolver Digital,"Austin, Texas",$135 million

In [7]:
def convert_to_int(value):
    value = value.replace('$', '').replace(',', '')
    if 'billion' in value:
        return int(float(value.replace(' billion', '')) * 1_000_000_000)
    elif 'million' in value:
        return int(float(value.replace(' million', '')) * 1_000_000)
    else:
        return int(value)

In [8]:
highest_revenue_companies['Revenue_Int'] = highest_revenue_companies['Revenue'].apply(convert_to_int)

In [10]:
highest_revenue_companies['Headquarter_Country'] = highest_revenue_companies['Headquarter'].str.split(', ').str[-1]

In [12]:
United States of America.Headquarter_Country.value_counts()

Headquarter_Country
Japan             10
California         7
South Korea        6
China              6
Sweden             4
France             4
New York           2
Washington         2
Israel             1
North Carolina     1
Singapore          1
Ireland            1
Poland             1
Canada             1
Florida            1
England            1
Texas              1
Name: count, dtype: int64

In [13]:
tis_a_thee_dictionary = {'California':'United States of America','New York':'United States of America','Washington':'United States of America','North Carolina':'United States of America','Florida':'United States of America','Texas':'United States of America'}

In [14]:
highest_revenue_companies['Headquarter_Country']=highest_revenue_companies['Headquarter_Country'].replace(tis_a_thee_dictionary)

In [15]:
highest_revenue_companies

,Rank,Company,Headquarter,Revenue,Revenue_Int,Headquarter_Country
0,1,Sony Interactive Entertainment,"San Mateo, California",$29.8 billion,29800000000,United States of America
1,2,Tencent Interactive Entertainment,"Shenzhen, China",$25.5 billion,25500000000,China
2,3,Microsoft Gaming,"Redmond, Washington",$21.5 billion,21500000000,United States of America
3,4,Nintendo,"Kyoto, Japan",$11.6 billion,11600000000,Japan
4,5,NetEase Games,"Hangzhou, China",$11.5 billion,11500000000,China
5,6,Electronic Arts,"Redwood City, California",$7.6 billion,7600000000,United States of America
6,7,Epic Games,"Cary, North Carolina",$5.8 billion,5800000000,United States of America
7,8,Take-Two Interactive,"New York City, New York",$5.3 billion,5300000000,United States of America
8,9,Embracer Group,"Karlstad, Sweden",$4.0 billion,4000000000,Sweden
9,10,MiHoYo,"Shanghai, China",$3.8 billion,3800000000,China
10,11,Roblox Corporation,"San Mateo, California",$2.8 billion,2800000000,United States of America
11,12,Playtika,"Herzliya, Israel",$2.57 billion,2570000000,Israel
12,13,Ubisoft,"Saint-Mandé, France",$2.5 billion,2500000000,France
13,14,Nexon,"Minato-ku, Tokyo, Japan",$2.48 billion,2480000000,Japan
14,15,37Games,"Shanghai, China",$2.3 billion,2300000000,China
15,16,Square Enix,"Shinjuku, Japan",$2.29 billion,2290000000,Japan
16,17,Oculus Studios,"Menlo Park, California",$2.16 billion,2160000000,United States of America
17,18,Bandai Namco Entertainment,"Minato, Tokyo, Japan",$2.1 billion,2100000000,Japan
18,19,Sega,"Shinagawa, Japan",$2.04 billion,2040000000,Japan
19,20,Netmarble,"Seoul, South Korea",$2.0 billion,2000000000,South Korea
20,21,NCSoft,"Pangyo, South Korea",$1.99 billion,1990000000,South Korea
21,22,Konami Digital Entertainment,"Ginza, Japan",$1.6 billion,1600000000,Japan
22,23,Krafton,"Seongnam, South Korea",$1.43 billion,1430000000,South Korea
23,24,Perfect World,"Beijing, China",$1.15 billion,1150000000,China
24,25,Garena,Singapore,$1.14 billion,1140000000,Singapore
25,26,NetDragon Websoft,"Fuzhou, China",$1.11 billion,1110000000,China
26,27,Wizards of the Coast,"Renton, Washington",$1.0 billion,1000000000,United States of America
27,28,Scopely,"Culver City, California",$1.0 billion,1000000000,United States of America
28,29,Capcom,"Chūō-ku, Osaka, Japan",$978 million,978000000,Japan
29,30,Keywords Studios,"Leopardstown, Ireland",$780 million,780000000,Ireland
30,31,Kakao Games,"Jeju, South Korea",$725 million,725000000,South Korea
31,32,Niantic,"San Francisco, California",$671 million,671000000,United States of America
32,33,Koei Tecmo,"Yokohama, Japan",$536 million,536000000,Japan
33,34,Gameloft,"Paris, France",$338 million,338000000,France
34,35,CD Projekt Red,"Warsaw, Poland",$311 million,311000000,Poland
35,36,Playstudios,"San Francisco, California",$310 million,310000000,United States of America
36,37,Tilting Point,"New York City, New York",$285 million,285000000,United States of America
37,38,Thunderful Group,"Gothenburg, Sweden",$274 million,274000000,Sweden
38,39,Pearl Abyss,"Gwacheon, South Korea",$260 million,260000000,South Korea
39,40,Neowiz Games,"Gyeonggi, South Korea",$250 million,250000000,South Korea
40,41,Paradox Interactive,"Stockholm, Sweden",$248 million,248000000,Sweden
41,42,Marvelous,"Shinagawa, Japan",$190 million,190000000,Japan
42,43,Enad Global 7,"Stockholm, Sweden",$187 million,187000000,Sweden
43,44,Focus Entertainment,"Paris, France",$187 million,187000000,France
44,45,Nacon,"Lesquin, France",$170 million,170000000,France
45,46,Behaviour Interactive,"Montreal, Canada",$163 million,163000000,Canada
46,47,Saber Interactive,"Fort Lauderdale, Florida",$161 million,161000000,United States of America
47,48,FromSoftware,"Tokyo, Japan",$152 million,152000000,Japan
48,49,Team17,"Wakefield, England",$151 million,151000000,England
49,50,Devolver Digital,"Austin, Texas",$135 million,135000000,United States of America

In [ ]:
highest_revenue_companies.info